export const PERSON_EVIDENCE_DENSITY = {
  standard: {
    width: 760,
    top: 224,
    portraitSize: 132,
    identityMarkSize: 116,
    fallbackIconSize: 70,
    brandIconSize: 48,
    identityGap: 22,
    nameFontSize: 36,
    roleFontSize: 22,
    roleLetterSpacing: 2.8,
    quoteFontSize: 24,
    quoteMaxWidth: 500,
    evidenceEyebrowFontSize: 22,
    evidenceTitleFontSize: 27,
    evidenceMetaFontSize: 24,
    timelineFontSize: 24,
  },
  mobile: {
    width: 900,
    top: 176,
    portraitSize: 208,
    identityMarkSize: 192,
    fallbackIconSize: 108,
    brandIconSize: 68,
    identityGap: 34,
    nameFontSize: 54,
    roleFontSize: 30,
    roleLetterSpacing: 1.6,
    quoteFontSize: 36,
    quoteMaxWidth: 640,
    evidenceEyebrowFontSize: 28,
    evidenceTitleFontSize: 34,
    evidenceMetaFontSize: 28,
    timelineFontSize: 28,
  },
} as const;
