import type { TerminologyEntry } from "./types.ts";

export const globalTerminology: TerminologyEntry[] = [
  {
    id: "seanlab",
    kind: "brand",
    domains: ["global"],
    canonicalZh: "SeanLab",
    canonicalEn: "SeanLab",
    sourceVariants: ["Sean Lab", "XianLab", "Xian Lab", "Xi'anLab", "Xi'an Lab", "西安Lab"],
    safeAsrCorrection: true,
  },
  {
    id: "workflow-zh",
    kind: "technical",
    domains: ["global"],
    canonicalZh: "工作流",
    canonicalEn: "workflow",
    sourceVariants: ["工做流"],
    safeAsrCorrection: true,
  },
  {
    id: "lims",
    kind: "technical",
    domains: ["global"],
    canonicalZh: "LIMS",
    canonicalEn: "LIMS",
    sourceVariants: ["Limits", "limits", "林姆斯"],
    safeAsrCorrection: true,
  },
  {
    id: "remotion",
    kind: "product",
    domains: ["global"],
    canonicalZh: "Remotion",
    canonicalEn: "Remotion",
    sourceVariants: ["remotion", "瑞莫申"],
    safeAsrCorrection: true,
  },
  {
    id: "xiaomi-mimo",
    kind: "product",
    domains: ["global"],
    canonicalZh: "小米 MiMo",
    canonicalEn: "Xiaomi MiMo",
    sourceVariants: ["小米mimo", "小米 Mimo", "mimo模型"],
    safeAsrCorrection: true,
  },
  {
    id: "visual-brief",
    kind: "technical",
    domains: ["global"],
    canonicalZh: "VisualBrief",
    canonicalEn: "VisualBrief",
    sourceVariants: ["visual brief", "Visual Brief", "视觉brief"],
    safeAsrCorrection: true,
  },
];

export const aiSoftwareTerminology: TerminologyEntry[] = [
  {
    id: "andrew-ng",
    kind: "person",
    domains: ["ai-software"],
    canonicalZh: "吴恩达",
    canonicalEn: "Andrew Ng",
    sourceVariants: ["伍恩达"],
    safeAsrCorrection: true,
  },
  {
    id: "fei-fei-li",
    kind: "person",
    domains: ["ai-software"],
    canonicalZh: "李飞飞",
    canonicalEn: "Fei-Fei Li",
    sourceVariants: ["李菲菲"],
    safeAsrCorrection: true,
  },
  {
    id: "chatgpt",
    kind: "product",
    domains: ["ai-software"],
    canonicalZh: "ChatGPT",
    canonicalEn: "ChatGPT",
    sourceVariants: ["chat gpt", "Chat G P T", "恰特GPT"],
    safeAsrCorrection: true,
  },
  {
    id: "claude-code",
    kind: "product",
    domains: ["ai-software"],
    canonicalZh: "Claude Code",
    canonicalEn: "Claude Code",
    sourceVariants: ["claude code", "克劳德code", "克劳德 Code"],
    safeAsrCorrection: true,
  },
  {
    id: "deepseek",
    kind: "product",
    domains: ["ai-software"],
    canonicalZh: "DeepSeek",
    canonicalEn: "DeepSeek",
    sourceVariants: ["deep seek", "Deep Seek", "深度seek"],
    safeAsrCorrection: true,
  },
  {
    id: "gemini",
    kind: "product",
    domains: ["ai-software"],
    canonicalZh: "Gemini",
    canonicalEn: "Gemini",
    sourceVariants: ["Gemlight", "gemlight", "杰米奈"],
    safeAsrCorrection: true,
  },
  {
    id: "github",
    kind: "product",
    domains: ["ai-software"],
    canonicalZh: "GitHub",
    canonicalEn: "GitHub",
    sourceVariants: ["github", "Git Hub", "基特哈布"],
    safeAsrCorrection: true,
  },
  {
    id: "ollama",
    kind: "product",
    domains: ["ai-software"],
    canonicalZh: "Ollama",
    canonicalEn: "Ollama",
    sourceVariants: ["ollama", "欧拉马", "奥拉马"],
    safeAsrCorrection: true,
  },
  {
    id: "omlx",
    kind: "product",
    domains: ["ai-software"],
    canonicalZh: "OMLX",
    canonicalEn: "OMLX",
    sourceVariants: ["omlx", "O M L X"],
    safeAsrCorrection: true,
  },
];

export const financeMarketsTerminology: TerminologyEntry[] = [
  {
    id: "sk-hynix",
    kind: "company",
    domains: ["finance-markets"],
    canonicalZh: "SK 海力士",
    canonicalEn: "SK hynix",
    sourceVariants: ["海力土", "SK海力士"],
    safeAsrCorrection: true,
  },
  {
    id: "a-share",
    kind: "technical",
    domains: ["finance-markets"],
    canonicalZh: "A股",
    canonicalEn: "A-shares",
    sourceVariants: ["a股", "A 股"],
    safeAsrCorrection: true,
  },
  {
    id: "sp-500",
    kind: "technical",
    domains: ["finance-markets"],
    canonicalZh: "标普 500",
    canonicalEn: "S&P 500",
    sourceVariants: ["标普500", "标普五百", "S P 500"],
    safeAsrCorrection: true,
  },
  {
    id: "nasdaq",
    kind: "technical",
    domains: ["finance-markets"],
    canonicalZh: "纳斯达克",
    canonicalEn: "Nasdaq",
    sourceVariants: ["纳指达克", "纳斯达客"],
    safeAsrCorrection: true,
  },
  {
    id: "basis-point",
    kind: "unit",
    domains: ["finance-markets"],
    canonicalZh: "基点",
    canonicalEn: "basis points",
    sourceVariants: ["机点", "基 点"],
    safeAsrCorrection: true,
  },
  {
    id: "price-earnings-ratio",
    kind: "technical",
    domains: ["finance-markets"],
    canonicalZh: "市盈率",
    canonicalEn: "price-to-earnings ratio",
    sourceVariants: ["市赢率", "市营率"],
    safeAsrCorrection: true,
  },
];

export const laboratoryBiopharmaTerminology: TerminologyEntry[] = [
  {
    id: "mobile-phase",
    kind: "technical",
    domains: ["laboratory-biopharma"],
    canonicalZh: "流动相",
    canonicalEn: "mobile phase",
    sourceVariants: ["流动向液", "流动向", "流动项", "流动像"],
    safeAsrCorrection: true,
  },
  {
    id: "baseline-stability",
    kind: "technical",
    domains: ["laboratory-biopharma"],
    canonicalZh: "基线稳定",
    canonicalEn: "baseline stability",
    sourceVariants: ["机械稳定", "基限稳定"],
    safeAsrCorrection: true,
  },
  {
    id: "liquid-chromatography",
    kind: "technical",
    domains: ["laboratory-biopharma"],
    canonicalZh: "液相色谱",
    canonicalEn: "liquid chromatography",
    sourceVariants: ["液向色谱", "液相色普"],
    safeAsrCorrection: true,
  },
  {
    id: "main-peak-purity",
    kind: "technical",
    domains: ["laboratory-biopharma"],
    canonicalZh: "主峰纯度",
    canonicalEn: "main-peak purity",
    sourceVariants: ["主风纯度", "主峰存度"],
    safeAsrCorrection: true,
  },
];

export const domainCatalog = {
  "ai-software": aiSoftwareTerminology,
  "finance-markets": financeMarketsTerminology,
  "laboratory-biopharma": laboratoryBiopharmaTerminology,
} as const;
